name: CI/CD Pipeline

# Trigger this workflow on every push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # The environment in which the job will run

    steps:
      # Checkout the latest code from your repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js environment (change the version if needed)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Run tests (if applicable, otherwise remove this step)
      - name: Run tests
        run: npm test

      # Deploy to AWS S3 (if applicable)
      - name: Deploy to AWS S3
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws s3 sync . s3://your-bucket-name
